### PR TITLE
feat: Implemented transformer for the wavedrom library

### PR DESCRIPTION
**Pull request by alexandruradovici**
# Description

This pull request implements a transformer for the wavedrom library. It allows writing waveform diagrams in the slides.

This allows writing wavefrom diagrams using the `wavedrom` transformer.

````md
```wavedrom
{signal: [
  {name: 'clk', wave: 'p.....|...'},
  {name: 'dat', wave: 'x.345x|=.x', data: ['head', 'body', 'tail', 'data']},
  {name: 'req', wave: '0.1..0|1.0'},
  {},
  {name: 'ack', wave: '1.....|01.'}
]}
```
````

## Why

This is useful when creating engineering slides. Without this feature, users have to manually transform the waveform JSON into SVG files and include those.

## Disadvantages
- `wavedrom`, `onml` and `json5` dev dependencies
- `onml` depends on two deprecated packages

### CODE REVIEW

**Comment by KermanX** [comment]
Thanks for your contribution! Can this feature be used as a standalone addon package? If not, what's the missing hook?

**Comment by alexandruradovici** [comment]
I think it can be an addon, I just don't know where to find the documentation on how to use a hook. I would be very happy to convert it.

**Comment by KermanX** [comment]
About addon writing: https://sli.dev/addons/write-an-addon

You can have setup and components folder in your addon, just like in your slides folder.

**Comment by alexandruradovici** [comment]
I saw this, but is there any API documentation?

**Comment by KermanX** [comment]
Here we can register a markdown-it plugin for waredrom: https://sli.dev/custom/config-vite#configure-internal-plugins

**Comment by alexandruradovici** [comment]
I am sorry, I still do not understand how to connect my plugin to slidev. 

1. I created a new package 
2. I added slidev as a dependecy

How to I make it initialize my plugin?

This is really confusing here, an API documentation and example would be great.

**Comment by antfu** [comment]
This looks very cool! But yeah I agree with @KermanX, I also think it's better to implement it as an external addon.

**Comment by KermanX** [comment]
> I am sorry, I still do not understand how to connect my plugin to slidev.
> 
> 1. I created a new package
> 2. I added slidev as a dependecy
> 
> How to I make it initialize my plugin?
> 
> This is really confusing here, an API documentation and example would be great.

There seem to be some difficulties in having a custom transformer... The priority of markdown-it plugins are too low. The preparser may help, but I don't think it is graceful enough. Maybe we need a `setupTransformers` like this:

```ts
type MarkdownTransfromer = (ctx: MarkdownTransformContext) => void
type TransformersSetup = (transformers: MarkdownTransfromer[]) => MarkdownTransfromer[]
```

**Comment by KermanX** [comment]
Sorry for the late reply. These days several refactors are done and I've tested that after #1767 got merged, this PR can be implemented as an add-on in a simple way.

**Pull request closed without merging**
