### PR TITLE
feat: add bottom area to two-cols-header layout

### PR DESCRIPTION
**Pull request by JPustkuchen**
See https://github.com/slidevjs/slidev/discussions/1113

`.col-bottom { grid-area: 3 / 3 / 2 / 3; }` is presumably still wrong, I'm not doing enough CSS ;)
Will send an update!

### CODE REVIEW

**Comment by thomasfrobieter** [comment]
Lacking context of the given grid-template (on the wrapper). However, I assume you have a 4x4 grid and you try to position .col-bottom in the right bottom, so its:

`grid-area: 3 / 3 / 5 / 5;`

**Comment by thomasfrobieter** [comment]
So, its a 

- Header (full width)
- Col left (50%), Col right (50%)
- Footer (full width)

Grid. If the HTML markup is in the right order, you dont need grid-row. 
So the code should be:

```
.col-header,
.col-bottom { grid-column: -1/1; }
.col-left,
.col-right { grid-column: span 2; }
```

Untested.

**Comment by JPustkuchen** [comment]
Thanks, @thomasfrobieter, I changed the code accordingly! Will still have to test this.

**Comment by JPustkuchen** [comment]
Whaooo cool, thank you @antfu never expected this might get merged :)

**Comment by adamdehaven** [comment]
@antfu this PR merge broke the `two-cols-header` layout. Content is no longer displayed in two columns under the header.

**Comment by antfu** [comment]
Would be appreciated if someone could send a fix.

**Comment by adamdehaven** [comment]
It's just an issue with the columns. I'm traveling to VueConf Toronto in the morning and should have some time while I'm waiting on flights if someone doesn't beat me to it.

**Comment by JPustkuchen** [comment]
Sorry.

Perhaps better revert this for now and instead, we add an *additional and better tested* two-cols-header-footer layout, once we have the reason?

Sorry no idea yet, why I didn't see this breaking. I'm going to take a look asap, very full timetable this week :(

**Comment by adamdehaven** [comment]
@antfu I believe [this PR should resolve](https://github.com/slidevjs/slidev/pull/1189) (please test the layout)

Also, thanks for **Sli**dev! I used it for my talk today at VueConf Toronto 🙌🏼 🎉

**Pull request merged**
