### PR TITLE
docs: fix home page button style

### PR DESCRIPTION
**Pull request by supermxscr**

### CODE REVIEW

**Comment by KermanX** [comment]
What did the buttons look like? I can't find the difference🥹

**Comment by supermxscr** [comment]
> What did the buttons look like? I can't find the difference🥹

image

**Review by KermanX — APPROVED** [review]
Although I am not able to reproduce this, I can now remember someone once reported this problem on the Discord server. Thank you for this fix!

**Comment by supermxscr** [comment]
> Although I am not able to reproduce this, I can now remember someone once reported this problem on the Discord server. Thank you for this fix!

That person is also me.

**Pull request merged**
