### PR TITLE
chore: use pnpm catalog

### PR DESCRIPTION
**Pull request by btea**
https://pnpm.io/catalogs

### CODE REVIEW

**Comment by KermanX** [comment]
Does https://github.com/antfu-collective/taze support PNPM catalog?

**Comment by btea** [comment]
I checked the code and it seems that it is not supported at present.

**Comment by btea** [comment]
@KermanX I created a PR. https://github.com/antfu-collective/taze/pull/123

**Comment by antfu** [comment]
We you like to help solving the conflicts, or redo the PR? Thanks

**Comment by KermanX** [comment]
The problem is that our smoke test CI needs to pack the packages. Not sure why `pnpm pack` doesn't resolve `catelog:` protocol.

**Comment by btea** [comment]
There were a lot of conflicts, so I created a new PR #1820.

**Comment by btea** [comment]
> The problem is that our smoke test CI needs to pack the packages. Not sure why `pnpm pack` doesn't resolve `catelog:` protocol.

According to the error message, it seems that npm was used to install dependencies, but npm does not support the `catalog` protocol.

**Pull request closed without merging**
