### PR TITLE
Add gap between columns in two-cols-* layouts

### PR DESCRIPTION
**Pull request by LostKobrakai**
This way the background of code boxes don't butt against each other.

### CODE REVIEW

**Comment by antfu** [comment]
I am not very sure. I feel it should leave to the users to decide.

**Comment by LostKobrakai** [comment]
That arguments kinda works in both ways. The user can customize the default by adding or removing any gap. I however think having a gap is the better default over not having a gap.

**Comment by LostKobrakai** [comment]
You can hack one in easier (margin on both columns), but adding a gap using the proper css (where it's one space properly aligned) takes the same amount of work of a custom layout as far as I see.

**Comment by YuanYuYuan** [comment]
I second this. It would be great to have an appropriate gap by default.

**Comment by maurer2** [comment]
Hello, I solved it by creating a custom layout `two-cols-with-gap.vue` in the layouts folder:

```vue
<script setup lang="ts">
const props = defineProps({
  class: {
    type: String,
  },
})
</script>

<template>
  <div class="slidev-layout w-full h-full">
    <div class="grid grid-cols-2 gap-4">
      <div class="col-left" :class="props.class">
        <slot name="left" />
      </div>
      <div class="col-right" :class="props.class">
        <slot name="right" />
      </div>
    </div>
  </div>
</template>
```

The new layout can then be applied in a slide like so:

```md
---
layout: two-cols-with-gap
hideInToc: true
---
```

Cheers

**Pull request closed without merging**
