### PR TITLE
fix(v-click-hide): the route for v-click-hide

### LINKED ISSUE #323: v-click-hide not working
**Describe the bug**
I have added the following div to make the text disappear after a click as explained in the documentation but it is not working
<div v-click-hide>Hello</div>

**To Reproduce**
Add the following slide
```
# Hello

<v-click>

Hello World

</v-click>

<div v-click-hide>

Hello

</div>

<v-click>

Hello Again

</v-click>
```

I have also tried to use it in one line `<div v-click-hide>Hello</div>` but this also does not work.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera
 - Slidev version: 0.22.4

### PR DESCRIPTION
**Pull request by WingLim**
`v-click-hide` route not work, because `elements` has nothig.

Fix it as how `v-click` work.

Fix #323.

### CODE REVIEW

**Comment by antfu** [comment]
Sorry I am a bit out-of-context right now. Does this PR still relevant?

**Comment by WingLim** [comment]
> Sorry I am a bit out-of-context right now. Does this PR still relevant?

The `v-click-hide` hide all element, instead of one by one.
Because there has no `elements` to control it.

**Comment by WingLim** [comment]
However, may be we could remove `v-click-hide`, because the `v-click` directive has already has the `hide` option to hide one element and show after one click.

**Comment by WingLim** [comment]
And this pr could fix #323.

**Review by antfu — APPROVED** [review]

**Pull request merged**
