### PR TITLE
fix: styles for rtl languages

### PR DESCRIPTION
**Pull request by tonai**
Fixes https://github.com/slidevjs/slidev/issues/834

### CODE REVIEW

**Comment by tonai** [comment]
Maybe we need a way to add `dir="rtl"` globally when writting a presentation in a language like arabic ?

**Comment by antfu** [comment]
> Maybe we need a way to add `dir="rtl"` globally when writting a presentation in a language like arabic ?

Maybe `rtl: true` option in the frontmatter?

**Comment by tonai** [comment]
> > Maybe we need a way to add `dir="rtl"` globally when writting a presentation in a language like arabic ?
> 
> Maybe `rtl: true` option in the frontmatter?

Can be, but when we think about it we should probably do the same thing for the `lang` attrbute.
So either:

* we add 2 attributes in the frontmatter, one for `dir` and another one for `lang` (and another one for another futur attribute ?)
* we add a `html` frontmatter attribute where you can add attributes that will be applied to the `html` element. Example:
  ```md
  ---
  html:
    dir: rtl
    lang: ar
  ---
  ```
* we provide a way to customize the `index.html`, in fact this is already possible to add things in the `head` and in the `body`, but we could maybe also use that file to customize `html` attributes.

**Comment by antfu** [comment]
```yaml
htmlAttrs:
  dir: rtl
  lang: ar
```

Probably more specific? In general I think it's a good idea

**Pull request merged**
